services:
  database:
    image: postgres:17-alpine
    container_name: next-church-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next_church
    volumes:
      - local_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U user -d next_church]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  local_db_data:
